### ISSUE TITLE
Change "Compare" output labeling

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#1027]
Compare box edge weight similarity comparison has an option labeled "Scheines Score". It should instead be labeled "Sum of squared differences of edge weights"

**Comment by jdramsey** [comment]
I am wondering whether this needs to be fixed. It seems to be a secret bug that only I know about.

**Comment by cg09** [comment]
Which is?

**Comment by jdramsey** [comment]
That is you (on a Mac) use command-Q to quit the problem, you could corrupt the session file, because that's not a Java command key sequence, it's a Mac sequence, and overrides Java. I have no idea how to fix it; I tried before, with no success. What will happen is you will think you're saving the session but you will not succeed. The session will be corrupted, and you won't be able to load it again. Insidious. But apparently I alone am bothered by this. You've never been.
