### ISSUE TITLE
Add undirected edge button in the Graph box.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1031]
Currently the only way to make an undirected edge in the graph box is to make some other type of edge and shift click the endpoints to make them both tails.

**Comment by cg09** [comment]
Since this issue was posted, we have been getting comments and requests from users (including users important to us) about rendering undirected edges in graphs. Please, please.

**Comment by MikeKonrad** [comment]
I'm one of those users, I believe!

As input to another Tetrad feature or just simply to create a pattern as part of a report, I often need to specify the nodes and edges for a pattern in Tetrad. Why isn't there an undirected edge button? Earlier versions of Tetrad had it. Also, I think you could click on the end of an arrow and turn that end into an undirected, which no longer works. Some mechanism for this is needed. Right now, I can build PAGs but not Patterns. 

[Sorry, I wasn't aware that this was already raised as an issue but discovered it as I tried to open one this morning on this same topic. I accidentally hit "return" before clicking on Joe's issue to add a comment, and as a result I closed the issue I opened because I didn't know how else to delete it or get it out of the issue tracking system.]

Anyway, bring back the undirected edge feature, please!!

**Comment by yuanzhou** [comment]
@jdramsey @cg09 I'm adding the undirected edge back to the graph editor. Is there any chance you can send me an icon for that edge type? I searched around different versions of tetrad and couldn't find it.

It's a gif with transparent background. 

![Capture](https://user-images.githubusercontent.com/195873/58581133-cfe38380-821c-11e9-8e0b-e17f9d989d24.PNG)

Another question is in the code I've seen the edge with two circles on each end being named "nondirected", but I've also seen some icons named as "unoriented". We are not showing the text in those icons currently. I just wanted to know the correct terminology.

**Comment by jdramsey** [comment]
@yuanzhou We never had an icon for an unoriented edge--I think you can just use a pixellator though to change the directed edge icon into an undirected edge icon.

**Comment by jdramsey** [comment]
This is beautiful! No, the other graph interfaces don't need an undirected edge type.

**Comment by yuanzhou** [comment]
@jdramsey cool, I'll send a pull request for your review shortly.

**Comment by jdramsey** [comment]
We have this now! :)
