### ISSUE TITLE
Refactoring getParameters() Method

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1106]
I have a proposition.  What are your thoughts on refactoring the getParameters() method so that when calling the method of the algorithm class, it only returns the parameters of the algorithm and not the combined parameters of test and/or scores?  By doing this we can get a specific parameters for test, scores, and algorithms so that we can categorize the parameters in the parameter panel.

**Comment by yuanzhou** [comment]
I like this idea and it'll make those parameters more organized for any updates. @kvb2univpitt also pointed out that we can put all the algo parameters into a enum class and call them in different places instead of hard-coding the string value.

**Comment by jdramsey** [comment]
I see, so you'll just get the parameters for the test from the test.... that seems OK.

**Comment by yuanzhou** [comment]
@jdramsey we are refactoring the parameters by 

- Making all parameters used by tests/scores/algorithms constants to avoid typos and hardcoding
- Categorizing the parameters by test, score, algorithm, bootstraping in the algo chooser parameters panel so the users know which parameter does what

I'm in the process of replacing all the hard-coded parameter strings with their constants. And I've seen some parameters being used in the algorithms that we are not showing int he algo chooser. Basically because we didn't annotate that algorithm wrapper. Should I just delete those unused algo wrapper classes? Are we gonna ever enable them again?

**Comment by yuanzhou** [comment]
@jdramsey I'm sure some of them are for experimental purposes, but there are some algos will probably be never used. Can you please take a look and tell me which one should I get rid off? Otherwise we'll have to maintain the parameters there.

**Comment by yuanzhou** [comment]
BTW, I'm also replacing those hard-coded parameters in simulation with their equivalent constants. And I did see a few typos. Some bugs could be caused by those parameter typos.
