### ISSUE TITLE
Tetrad 6.7.0 has dropped SEM BIC-based independence test (related to Issue #821)

### ISSUE THREAD

**Issue by MikeKonrad** [cmu-phil/tetrad#1195]
Should the SEM BIC based independence test be gone for constraint-based search? It was present in Tetrad 6.6.0 but not 6.7.0.

My understanding from an email exchange with Joe over a year ago is that when the data departs pretty significantly from Gaussian distribution, SEM BIC might be the better test to use than Fisher Z.

Is that still the current thinking? 

The discussion on Issue #821 suggests otherwise and also that there was an issue with SEM BIC. I hope this has been fixed. In Tetrad 6.6.0, SEM BIC is still offered as an alternative for basing an independence test. Can we rely on it?

Should Tetrad 6.7.0 include SEM BIC-based independence test?

Lots of questions, sorry, but also urgently needed.

**Comment by MikeKonrad** [comment]
I should generally be using FASK here, correct, instead of trying to use PC with SEM BIC for non-Gaussian but (mostly) linear data (under the additive noise model)?

**Comment by cg09** [comment]
Yes, FASK.  Clark

**Comment by jdramsey** [comment]
I talked with Mike about this--the issue is that with the new covariance matrix calculation, for GES SEM BIC always beats the Fisher Z score, under all scenarios, and for constraint-based algorithms, Fisher Z test always beats SEM BIC test, under all scenarios. So since we know this, Fisher Z score and SEM BIC test were taking out of the interface. It doesn't makes sense to suggest to the user that they should try each in turn, when we know which is dominant. This is a feature of the new Tetrad, not the old. (Tetrad 7?)
