### ISSUE TITLE
joe.work.2019.8: Unable to Manually Enter Data in the Data Box

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1202]
The data disappears when manually entering data into the data cell.

**Comment by jdramsey** [comment]
@kvb2univpitt OK, this is fixed for continuous data sets. So it works from a blank data editor, you can add new data and it will keep up with you and add missing value markers where necessary.

The problem was the data box resizing. This needs to be pushed down into the individual data boxes to get it to work with arbitrary data box types.

**Comment by cg09** [comment]
Yes, making a data set from scratch or adding a new column by hand might
sometimes be useful.

**Comment by cg09** [comment]
Sure I could. Can I save out a data object from TETRAD as an Excel file?  I
cannot.

**Comment by jdramsey** [comment]
This has been fixed! https://github.com/cmu-phil/tetrad/pull/1198
