### ISSUE TITLE
Problem with fges and imgs_cont in CMD 1.1.1

### ISSUE THREAD

**Issue by rubenSaro** [cmu-phil/tetrad#1225]
Hi,
In the new tetrad command line, 1.1.1.  when calling imgs_cont or fges, no option to control the penalty discount is available. 

Unrecognized option: --penaltyDiscount

**Comment by kvb2univpitt** [comment]
@rubenSaro Staring with Tetrad version 6.7.0, parameters for test and score are no long part of the algorithm's getParameters method.  Causal-cmd is still using the old way of getting the parameters for test and score through getParameters() method of the algorithm.

This is a causal-cmd issue.  I will close the issue here and reopen it in the causal-cmd repository.

**Comment by rubenSaro** [comment]
thanks Kevin

**Comment by kvb2univpitt** [comment]
@rubenSaro We made a release contain the fix: https://github.com/bd2kccd/causal-cmd/releases/tag/v1.1.2

**Comment by rubenSaro** [comment]
Awesome, thanks
