### ISSUE TITLE
Revised time series graph

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1231]
@cg09 @espinoj @kvb2univpitt 

I noticed the time series graphs we are making (my fault) in the Time Series Simulator option are a little unrealistic, since they allow parents from multiple previous lags into the current lag, whereas I've never seen this occur. Also, they don't have an option for disallowing edges among the lag 0 nodes. I have code where I've fixed the former problem, though I would need to add an option for the latter.  A third issue is that the self loops should be optional. I'd need to add that option (easy).

The idea would be as follows. You make a normal graph over the variables. Say the graph has an edge X->Y and the time lag graph is supposed to have 3 lags. Then you pick a random lag for that edge to be from, say 2, and add the edge X:2 -> Y to the time lag graph. If you want to include self loops, then you can include the edge X:1 -> Y to the graph. If you want to include edges among the time lags, then  take the random selection of lag from {0, 1, 2, 3} instead of {1, 2, 3}.

Then you can do the time series simulation as per usual.

This does not mean the search outputs will not include edges from multiple lags, even if it's correct.

Comments? If you like this idea, I can make a pull request whenever, it's mostly done.

Joe

**Comment by dmalinsk** [comment]
Hey Joe,

Sorry I don't check this github channel very often, but I just noticed this
message. I don't think I understand or fully agree with your proposal. It
sounds like you want the simulator to randomly pick some lag (2 in your
example) at which to add an edge (X:2 -> Y) at the expense of other lags. I
don't see why this should be the case. Typically time series models are
hierarchical: if it is order 2, then X:2 ->Y and X:1 -> Y and possibly X ->
Y (depending on whether you allow contemporaneous influence). If it is
order 3 then X:3 ->Y and X:2 ->Y and X:1 -> Y... It seems like you should
give the user an option to specify "order" which is the maximum lag number
p for which there is a directed edge between X:p to Y and it forces edges
for all p-1,p-2 if the X:p to Y edge exists.

I wrote some code for a certain time series simulator at some point for my
dissertation. I don't think it I ever pushed it to development branch and
I'm not sure if it is worth the trouble at this point, since so much has
changed in Tetrad there will be compatibility issues. But I'm happy to talk
about this sometime.

Best wishes,
Dan

**Comment by jdramsey** [comment]
It seems this issue has died. In the interest of getting a new version out I'm going to close this, but if it becomes an issue in the future, a new (more specific) issue can be created.
