### ISSUE TITLE
No drop-down for boolean variables

### ISSUE THREAD

**Issue by Dipakam** [cmu-phil/tetrad#1287]
Tried running ts-fci on a data after introducing the time lag. For setting the parameters it is not showing any drop down as it used to for the variables that are boolean. There is a manual text box in which I tried feeding up the value "no" but it is not working. 
It shows the following error. 
java.lang.RuntimeException: ERROR: Parameter verbose was not actually boolean

**Comment by jdramsey** [comment]
I just saw this. If I'm not too late, could I ask how you're running Tetrad? Are you building it in an IDE and running it? If that's the case, you always need to do a maven clean compile before launching it:

mvn clean compile

The reason is that the default parameter values are stored in the manual, and this maven compile copies them over so they can be used after you launch. When I see this:

java.lang.RuntimeException: ERROR: Parameter verbose was not actually boolean

it's a dead giveaway that the maven clean compile wasn't run.
