### ISSUE TITLE
cmd IMaGES not recognizing penaltyDiscount or score parameters

### ISSUE THREAD

**Issue by rubenSaro** [cmu-phil/tetrad#1293]
@espinoj @jdramsey @kvb2univpitt 

Hi all, I think this is related to a previous problem that went unsolved.

In tetrad cmd, v.1.1.3 (latest), the IMaGES algorithm does not recognize the --penaltyDiscount and the --score parameters.

Thanks,

Ruben

**Comment by kvb2univpitt** [comment]
Hi @rubenSaro.  Thanks for reporting this.  I'll take a look at it this weekend and get back to you.

**Comment by kvb2univpitt** [comment]
Hi @rubenSaro Sorry for the late reply.  What IMaGES algorithm are you using, discrete or continuous?  I am not seeing the problem on my end.  Can you please provide me the command-line?  Thank you.

**Comment by rubenSaro** [comment]
Hi Kevin,
If I use command-line v.1.0.0, it works, the problem is with v.1.1.3

I am using command-line v.1.1.3, with the following flags:

--thread 1000
--algorithm imgs_cont
--score sem_bic
--penaltyDiscount 1
--maxDegree 1000
--faithfulnessAssumed
--dataset "whateverDatasetYouHaveAtHand"
--no-header
--data-type continuous
--delimiter comma
--out "whateverDataDirectoryYouWant"
--prefix "whateverNameYouWant"

**Comment by kvb2univpitt** [comment]
@rubenSaro @jdramsey 

Ok.  The penaltyDiscount parameter definitely is working.  I just tested it.

The **imgs_cont** algorithm doesn't take a score parameter.  Looking at the code, if the numberResampling is less than 1, it will use **SemBicScoreImages** score internally.  Otherwise, it will use **ImagesSemBic** score internally.  The numberResampling parameter, however, is not exposed. (Joe, this might be a bug?)   So, by default, the numberResampling is 0 and the default score will be used internally is SemBicScoreImages.

Just remove the score parameter from the command-line.

**Comment by rubenSaro** [comment]
Ok, I will try it again, this time removing the score parameter, and
leaving the penaltyDiscount parameter.

Thanks Kevin.

R.

**Comment by kvb2univpitt** [comment]
I assumed this is no longer an issue.  Please re-open it if you're still having problem.
