### ISSUE TITLE
Difference between modules

### ISSUE THREAD

**Issue by ghost** [cmu-phil/tetrad#1322]
Greetings,

Based on the descriptions in the manual, I'm a bit confused as to what is the difference between the estimator and the instantiated module. As far as I understood the instantiated model assigns values to the parameters and the estimator also outputs an "instantiated" model of the data. Can someone clarify this?

Also, I wonder if there's a way to work with a batch function of sort in the GUI. Specifically, what if I want to run a multiple subjects at the same time?

Thanks!

**Comment by jdramsey** [comment]
Sorry, I got busy the last few months. Can I be of any help now? The difference between estimator and im is that the second estimates the first using a pm and data. In other words, you're estimating from data (instead of e.g. specifying a model without data).

There is an elaborate way to do batch work inside of Tetrad called the algorithm comparison tool. We wrote it up here:

Ramsey, J. D., Malinsky, D., & Bui, K. V. (2020). algcomparison: Comparing the Performance of Graphical Structure Learning Algorithms with TETRAD. Journal of Machine Learning Research, 21(238), 1-6.
