### ISSUE TITLE
Help on different results using different Tetrad releases

### ISSUE THREAD

**Issue by sgol17** [cmu-phil/tetrad#135]
Dear All,
I started to use Tetrad for my analysis when the available release was the 5.1.0-6.
I downloaded the current release (5.2.1-3) and I used the new release to the same dataset and I obtained results that are completely different. 
In attachment you can find the output of the two analysis. The data are the same, the constraints inserted through the knowledge box are the same, the searching algorithm is the same (PC with the same specifications) but the results are completely different. 
Which result do I have to trust?

Moreover, in the analysis performed with Tetrad 5.2.1-3, almost all the links between my variables are bidirected edges, suggesting the presence of latent common cause, which is not reasonable for all the edges, given the context of the variables.

Thank you for the help and the clarifications that yoo can give me.
Best Regards
Silvia Golia

[Report.pdf](https://github.com/cmu-phil/tetrad/files/126135/Report.pdf)

**Comment by jdramsey** [comment]
Sorry, I am just now getting back to looking at these issues. Bidirected edges with PC are unfortunately a problem with how the algorithm is defined; it's sensitive for example to the presence of latent variables and unfaithfulness. If you want to avoid all bidirected edges, use the FGS algorithm. We've submitted a paper for this for Plos One, but it's not published yet. There's a tech report on arXiv, which you can find by searching my name.

The differences between versions are due to a different (but equally correct) algorithm for doing the adjacency search. It just does it in a different order. If the data are faithful to the true graph, it will not produce a different result, but in the presence of unfaithfulness it might. Unfortunately, unfaithfulness is a common issue. Again, I would recommend you use FGS instead. If you want to use PC, I would do with the later versions, which have been more extensively tested.

The knowledge issue I'll try to fix.

**Comment by jdramsey** [comment]
I'm going to work on Knowledge today and tomorrow; several bugs have been reported; I just need to go through it carefully.

**Comment by jdramsey** [comment]
Another issue is just to consider which version is more accurate. I've been upgrading the simulation facilities to check this better, in the branch 'experimental'. Maybe once I get a little more done with this I'll do a simulation study for the version in the branch 'experimental'. That should be informative.

**Comment by jdramsey** [comment]
I take it you're no longer looking at this thread. If you are, reopen--I'm trying to get old issues cleaned up.
