### ISSUE TITLE
Handle missing value

### ISSUE THREAD

**Issue by lockmatrix** [cmu-phil/tetrad#1405]
When I try to process dataset with missing value, I get this:
```
Cutoffs should be in nondecreasing order: [0.0, NaN]
Cutoffs should be in nondecreasing order: [-6.378681, NaN]
```

algo mode:
`--algorithm fges --parallelized --data-type mixed --delimiter comma --missing-marker NULL --score cg-bic-score --numCategories 16 --verbose `

I guess maybe it is bug when processing dataset with missing value

**Comment by jdramsey** [comment]
Can you impute the missing values? In the Tetrad GUI testwise deletion is used for this case, though it is very slow. I supposed I could export that to tetrad-cmd...

**Comment by lockmatrix** [comment]
> In the Tetrad GUI testwise deletion is used for this case, though it is very slow. I supposed I could export that to tetrad-cmd...

I thought tetrad-cmd has this feature.
I'm trying this to see if I can get better result

**Comment by jdramsey** [comment]
Did you ever try this? @lockmatrix

**Comment by cg09** [comment]
No, I looked at it but there are no descriptions.

**Comment by jdramsey** [comment]
Oh I meant that for the guy who posted the report... he said he was going
to try something...

Joe

**Comment by lockmatrix** [comment]
> Did you ever try this? @lockmatrix

oh, I meant : I had already test a impute version. I was trying directly input the nullable data to see if I can get better result.

And I failed, got these message.

**Comment by jdramsey** [comment]
Ah. OK. I'll try to think about it some more then.

Thanks,

Joe

**Comment by jdramsey** [comment]
@lockmatrix  We just did a new release of Tetrad 7.1.3-1; the corresponding causal-cmd 1.5.0 will follow soon. But I was going back through issues and realized what the issue is here. Sorry, I wasn't thinking before. In the interface, if you have missing values, the testwise deletion API will kick in and do its thing. But that's not available in causal-cmd.

Could it be made available in causal-cmd? That I'd have to think about; we would have to change the way it's being handled in the GUI and make --testwise-deletion a flag for all scores and algorithms that can handle it. That would be a pretty big job, and we're working with a skeleton crew at the moment (mostly me, with some help from kind people). But what I'll do here for now is close out this issue and open another issue to remind me to try to think about that further. If a way occurs to me to do it more easily than what I've got in mind currently, I may give it a shot. -JR
