### ISSUE TITLE
RFCI appears to give different answers on different runs on the same data. (Double check.)

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1494]

**Comment by kvb2univpitt** [comment]
I would like to elaborate on that.  Using  IndTestProbabilistic test, RFCI should produce different graphs on multiple runs using the same data and parameters if no threshold is used.  This is because the  IndTestProbabilistic will determine if **x** and **y** are conditionally independent given **Z** based on coin flipping (random generator).  However, RFCI should produce same graphs on multiple runs using the same data and parameters with a fixed threshold.  This is because the  IndTestProbabilistic will determine if **x** and **y** are conditionally independent given **Z** based on comparing the posterior to the same threshold.

Below is a snippet to the IndTestProbabilistic code that determines the conditional independence:
```java
boolean ind;
if (threshold) {
    ind = (p >= cutoff);
} else {
    ind = RandomUtil.getInstance().nextDouble() < p;
}
```

**Comment by jdramsey** [comment]
I found a source of instability--RFCI was using FasConcurrent, which doesn't guarantee that the nodes in a depth will be visited in a fixed order, because of the concurrency, and so falls prey to the issues noted with PC Stable. Solution is either to use Fas instead (without the concurrency) or to use FasConcurrent, but set isStable(true). Opting for the former. Now, running two RFCI searches off of the same SEM Simulation and comparing the two results using the Edgewise Comparison shows that the results come out consistently the same. This is with Fisher Z.

**Comment by jdramsey** [comment]
Actually, 'stable' was set by default to true, which means the FasConcurrent in 'stable' mode wasn't always returning the same graph, which on the face of it should be impossible....

**Comment by jdramsey** [comment]
PR: https://github.com/cmu-phil/tetrad/pull/1496
