### ISSUE TITLE
How to format social science panel data for TETRAD input?

### ISSUE THREAD

**Issue by barrynuqoba** [cmu-phil/tetrad#1532]
Thank you for your excellent work on creating the TETRAD application. I use TETRAD to conduct experiments for my Ph.D. study. Specifically, I use it to derive causal graphs from social science panel data. The panel data that I use consist of more than 500 variables. It is fielded monthly (90 months in total), with around 7000 respondents continuously participating in the survey.

I only used a single month of data (cross-sectional) for the causal discovery experiment. I plan to use data from several months to derive the causal graph. How should I format the panel data to use the TETRAD method to derive the causal graph?

I really appreciate any help you can provide.

**Comment by barrynuqoba** [comment]
Hi Clark,

Thank you very much for your quick response and helpful suggestions. Yes, I am a faculty in Universitas Airlangga. Now, I am studying at Singapore Management University. I will try to format the data as you suggested. I previously used the GRaSP method in TETRAD for my experiments in cross-sectional data. It yields the result so fast. I will try to use FGES and GRaSP for the panel data. Maybe I will try it with a smaller number of variables first.

Thank you very much, Clark.

Best regards,
Barry

**Comment by jdramsey** [comment]
Barry,

One small hint is that you should use the latest version 7.2.2 of Tetrad; a bug was fixed in GRaSP for knowledge that will be helpful for dealing with panel data like that. Actually, there is an experimental algorithm called BOSS that you could use that will scale more easily up to that many variables, though it's not published yet, and the implementation is not yet fixed. FGES  can handle 500 variables and if the graph isn't too dense gives good results for that many variables.

If you're going to set up knowledge tiers yourself for that many variables, you may find it less anxiety-producing to create the text file yourself with the knowledge in it and load the text file in the knowledge box. You can practice by making some knowledge in the knowledge box and saving the knowledge out using the File menu in the Knowledge box to see the format, and then editing the text file.

Or what a lot of people prefer with that many variables--using causal-cmd instead--if you do, use version 1.6.1, the latest. Let us know--we can help you set that up if it would be helpful to you.

Joe

**Comment by barrynuqoba** [comment]
Hi Joe,

Thank you very much for your kind suggestions. Your detailed clarifications are very helpful. I will do as you suggested.

Have a great day!

Best regards,
Barry

**Comment by jdramsey** [comment]
Oh, you're welcome!! Let me know if you have problems.
