### ISSUE TITLE
Questions regarding the legality of a PAG

### ISSUE THREAD

**Issue by adam2392** [cmu-phil/tetrad#1556]
In the GUI of tetrad, when drawing an arbitrary graph, there is a menu item that says: "Add/Remove PAG coloring". 

My questions are:

1. What is the coloring exactly? The colors all stay the same as blue, so not sure if perhaps this means something else that I might be missing.
2. It asks if one wants to check the "legality of the PAG". How does the legality of the PAG get checked?

**Comment by jdramsey** [comment]
Perhaps "coloring" is no longer the apt description. We represented the "colors" as line width and line dashing. The idea is that if X-->Y is a _definitely direct_ edge (i.e., it would appear as a directed in the true PAG with latents), it is thick; otherwise, it is thin. And if it is a _no latent_ (i.e., "visible"), it is solid; if invisible, it is latent. The idea of a "visible" edge (see papers by Jiji Zhang, for instance), then X and Y are not confounded by any latent common cause, so this is an edge whose coefficient in principle (for a linear model) could be estimated.

This will only be clearly valid for PAGs, though you may find the information helpful (at your own risk) for other types of graphs.

As for the legal PAG condition, first one tries to find a MAG in the PAG using Zhang's algorithm. (If you need a reference for that let me know and I can get it for you). Then one checks to make sure the MAG is a legal MAG, and if so, one converts the MAG back into a PAG and sees if one recovers the original graph; if not, it's not a legal PAG (but could be a PAG with some additional orientations, for instance.)

A legal MAG cannot have any directed cycles or any almost cyclic paths. (An "almost cyclic" path is like X->Y<->Z->W->X, where if the Y<->Z edge were turned into Y->Z, there would be a cycle.) Also, the potential MAG here must be maximal, in the sense that there must not be an inducing path between any pair of adjacent variables in the graph.

If there are undirected (selection bias) edges in the graph, a further condition must be checked as well.

As you can imagine, checking these conditions for large graphs can be time-consuming, which is why we ask the user if they really want to do it.

**Comment by adam2392** [comment]
> Perhaps "coloring" is no longer the apt description. We represented the "colors" as line width and line dashing. The idea is that if X-->Y is a _definitely direct_ edge (i.e., it would appear as a directed in the true PAG with latents), it is thick; otherwise, it is thin. And if it is a _no latent_ (i.e., "visible"), it is solid; if invisible, it is latent. The idea of a "visible" edge (see papers by Jiji Zhang, for instance), then X and Y are not confounded by any latent common cause, so this is an edge whose coefficient in principle (for a linear model) could be estimated.

Makes sense. That's what I suspected, but wasn't sure if the coloring was something else that glitched out for me :p. Thanks for the explanation!

> As for the legal PAG condition, first one tries to find a MAG in the PAG using Zhang's algorithm. (If you need a reference for that let me know and I can get it for you). Then one checks to make sure the MAG is a legal MAG, and if so, one converts the MAG back into a PAG and sees if one recovers the original graph; if not, it's not a legal PAG (but could be a PAG with some additional orientations, for instance.)

I'm not aware of this algorithm. Is it in the "Causal Reasoning with Ancestral Graphs" paper? If you have the reference, that would be amazing. 

Would this algorithm checking be complete? I.e. if it return True, then it is forsure a valid PAG, but also if it returns False, then that means it is forsure not a valid PAG (maybe a PAG with some additional orientations). Or are there some valid/invalid PAGs that this checking might not work as we would like?

For context, I've been looking for an algorithm like this to make constructing small PAG examples more tractable. It's like mental gymnastics every time you want to construct a valid PAG with some specific edge sequence.

**Comment by jdramsey** [comment]
The PAG to MAG algorithm is in Zhang, J. (2008). On the completeness of orientation rules for causal discovery in the presence of latent confounders and selection bias. Artificial Intelligence, 172(16-17), 1873-1896, Theorem 2.

And yes, the algorithm checking is complete in this sense--if it says it's a PAG, it's a PAG, and if it says it's not a PAG it's not a PAG. It's not my algorithm, by the way. :) Peter Spirtes suggested it.

This would definitely help make small PAG examples! :) I hadn't thought of that :) I'd mainly been using it to check the results of various algorithms.

**Comment by adam2392** [comment]
A final question of clarification, in the final step "one converts the MAG back into a PAG and sees if one recovers the original graph; if not, it's not a legal PAG". This is essentially just re-running the FCI algorithm using the MAG as the oracle right?

**Comment by jdramsey** [comment]
Yes, though there is a much faster way to do a DAG to PAG as well (that will also work for MAG to PAG), also due to Peter Spirtes--just using inducing and directed inducing paths, but you could do it with FCI as well; you're right. Oh wait, this is for py-why-graphs? Doesn't py-why-causal-learn already have a DAG to PAG? Would that also do MAG to PAG?

If you have an inducing path method, you're 90% of the way there, and it's purely graphical. You use the inducing paths to calculate non-adjacencies, then use directed inducing paths to calculate unshielded colliders, and then apply Zhang's final orientation rules. It's much quicker.

By the way, there is a working version of this in Java code to calibrate against.

**Comment by adam2392** [comment]
> Yes, though there is a much faster way to do a DAG to PAG as well (that will also work for MAG to PAG), also due to Peter Spirtes--just using inducing and directed inducing paths, but you could do it with FCI as well; you're right. Oh wait, this is for py-why-graphs? Doesn't py-why-causal-learn already have a DAG to PAG? Would that also do MAG to PAG?

Ah okay yeah makes sense, since we have the "graph" already as the oracle, just add additional adjacencies due to inducing paths. So pywhy causal-learn has a DAGtoPAG, but I'm not sure if that works for MAG to PAG. Unsure because there is possibly some missing documentation on it. So I want to make sure that we have a correct implementation. 

However, this wouldn't work on a MAG, since by definition, a MAG doesn't have inducing paths between non-adjacent nodes?

We will try to eventually migrate most of the graph functionality into pywhy-graphs, so that way the graph algorithms can be developed in a centralized location together.

> If you have an inducing path method, you're 90% of the way there, and it's purely graphical. You use the inducing paths to calculate non-adjacencies, then use directed inducing paths to calculate unshielded colliders, and then apply Zhang's final orientation rules. It's much quicker.

I'm not familiar w/ the directed inducing path. Is there a reference for that?

**Comment by jdramsey** [comment]
It just means an inducing path from X to Y into Y--i.e.; it has an
arrowhead at Y.

**Comment by jdramsey** [comment]
Hi @adam2392 Can this issue be closed? Just doing a pass to clean up issues. If there are more questions I can leave it open, no problem.

**Comment by adam2392** [comment]
Sure!

**Comment by jdramsey** [comment]
Thanks!
