### ISSUE TITLE
I want an earlier version of tetrad-gui.

### ISSUE THREAD

**Issue by magical-hhc** [cmu-phil/tetrad#1569]
I want an earlier version of tetrad. For example, I need tetrad-gui-4.3.10. How can I get it? Because the new version of independence facts can't be found, I don't know how to realize the function of this plate.

**Comment by jdramsey** [comment]
I'm sorry; we no longer have those; the server that stored them died. We've moved all the recent versions to Maven Central, a more secure location. We explain the situation here:

https://sites.google.com/view/tetradcausal/faq

But can you explain the situation to me in a little more detail? I can help.

**Comment by jdramsey** [comment]
Actually, maybe you're looking for the gadget to show independence facts, which was moved to the Compare box. I took some screenshots to show how to use it. It's been generalized so that you can use wildcards "?" and "+" to list more than one independence fact.

<img width="723" alt="Screenshot 2023-03-26 at 8 06 31 AM" src="https://user-images.githubusercontent.com/9853255/227774627-5e85f364-2f73-4710-834c-809037d3187a.png">
<img width="474" alt="Screenshot 2023-03-26 at 8 06 44 AM" src="https://user-images.githubusercontent.com/9853255/227774628-2207c77e-48f6-4cb0-9880-f589aac38809.png">
<img width="718" alt="Screenshot 2023-03-26 at 8 07 02 AM" src="https://user-images.githubusercontent.com/9853255/227774629-f0887e72-e2bd-4c64-87b4-71d7bb60fa2c.png">
<img width="717" alt="Screenshot 2023-03-26 at 8 07 34 AM" src="https://user-images.githubusercontent.com/9853255/227774630-d803f54d-3887-4ec7-a4c0-1f24e9185090.png">

**Comment by magical-hhc** [comment]
Dear Joseph：
I'm glad you can reply to me. I learned about this software through the school, and I really hope to finish my graduation thesis with it.
Specifically, I now have a covariance matrix of a set of variables, and I need to draw its DAG diagram and get the correlation coefficient of 0-2 order between variables. As shown in the following figure, this blogger realized this function in tetrad 4.3.6, but I couldn't do it in tetrad 7.1.0, which bothered me for a long time. I read the official guide Tetrad Manual and didn't solve this problem.
I would appreciate it if you could help me solve this problem! !








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Joseph ***@***.***&gt;; 
发送时间: 2023年3月26日(星期天) 晚上7:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cmu-phil/tetrad] I want an earlier version of tetrad-gui. (Issue #1569)





 
I'm sorry; we no longer have those; the server that stored them died. We've moved all the recent versions to Maven Central, a more secure location. We explain the situation here:
 
https://sites.google.com/view/tetradcausal/faq
 
But can you explain the situation to me in a little more detail? I can help.

**Comment by magical-hhc** [comment]
Yes, that's what I want.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Joseph ***@***.***&gt;; 
发送时间: 2023年3月26日(星期天) 晚上8:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cmu-phil/tetrad] I want an earlier version of tetrad-gui. (Issue #1569)





 
Actually, maybe you're looking for the gadget to show independence facts, which was moved to the Compare box. I took some screenshots to show how to use it. It's been generalized so that you can use wildcards "?" and "+" to list more than one independence fact.
 

 

 

 

 
&mdash;

**Comment by jdramsey** [comment]
Great! Sorry, your figure didn't show in the message (or in your email); could you try again? Or could I just show you how to load a covariance matrix and do a search and estimation?

**Comment by magical-hhc** [comment]
INV	GE	M2	CR
1.0000	0.2860	0.2080	-0.2360
0.2860	1.0000	0.1820	0.1060
0.2080	0.1820	1.0000	0.1780
-0.2360	0.1060	0.1780	1.0000



The above is the disturbance correlation coefficient matrix between the four variables calculated by SVAR model. Next, I want to use PC algorithm to get the DAG diagram, and then find the 0-2 order correlation between variables.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Joseph ***@***.***&gt;; 
发送时间: 2023年3月26日(星期天) 晚上8:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cmu-phil/tetrad] I want an earlier version of tetrad-gui. (Issue #1569)





 
Great! Sorry, your figure didn't show in the message (or in your email); could you try again? Or could I just show you how to load a covariance matrix and do a search and estimation?
 
&mdash;

**Comment by jdramsey** [comment]
Do you know the sample size?

**Comment by magical-hhc** [comment]
The sample size is 60.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Joseph ***@***.***&gt;; 
发送时间: 2023年3月26日(星期天) 晚上8:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cmu-phil/tetrad] I want an earlier version of tetrad-gui. (Issue #1569)





 
Do you know the sample size?
 
&mdash;

**Comment by jdramsey** [comment]
OK, let me reformat your correlation matrix with that sample size for loading in Tetrad. I'll attach it by email.

**Comment by magical-hhc** [comment]
Thank you very much for your help.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Joseph ***@***.***&gt;; 
发送时间: 2023年3月26日(星期天) 晚上8:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cmu-phil/tetrad] I want an earlier version of tetrad-gui. (Issue #1569)





 
OK, let me reformat your correlation matrix with that sample size for loading in Tetrad. I'll attach it by email.
 
&mdash;

**Comment by jdramsey** [comment]
Absolutely! I made the covariance matrix data set for you in Tetrad format and made a Tetrad session that will load in version 7.3.0 of Tetrad. I had to zip the directory to attach it to this issue; let me know if you're able to unzip it on your machine.

[for-magical-hhc.zip](https://github.com/cmu-phil/tetrad/files/11071597/for-magical-hhc.zip)

**Comment by jdramsey** [comment]
Since the sample size was small, I used a high alpha level for my example of 0.3; you may try varying the alpha level. Here's where I set it, in the Search box:

<img width="849" alt="Screenshot 2023-03-26 at 8 47 46 AM" src="https://user-images.githubusercontent.com/9853255/227776742-9299269c-a9f1-4a54-a327-a74ff5622056.png">

**Comment by jdramsey** [comment]
Oh wait, maybe you meant for the alpha level to be set to 0.2--you can make that adjustment.

**Comment by magical-hhc** [comment]
I think my problem has been solved, and I would like to express my heartfelt thanks to you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Joseph ***@***.***&gt;; 
发送时间: 2023年3月26日(星期天) 晚上8:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cmu-phil/tetrad] I want an earlier version of tetrad-gui. (Issue #1569)





 
Oh wait, maybe you meant for the alpha level to be set to 0.2--you can make that adjustment.
 
&mdash;

**Comment by magical-hhc** [comment]
Dear Joseph：
I have a little suggestion, I don't know if it is reasonable. If you can read the process of dealing with the difficulties encountered by users in using tetrad somewhere on the website, I think others can avoid similar problems from happening again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Joseph ***@***.***&gt;; 
发送时间: 2023年3月26日(星期天) 晚上8:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cmu-phil/tetrad] I want an earlier version of tetrad-gui. (Issue #1569)





 
Oh wait, maybe you meant for the alpha level to be set to 0.2--you can make that adjustment.
 
&mdash;

**Comment by jdramsey** [comment]
That's a great idea--you know, you can search the issues in Tetrad to see if anyone else has asked the same question--here's an example. For instance, if I search for "Independence," your issue is listed as the most recent.

<img width="1428" alt="Screenshot 2023-03-26 at 9 01 20 AM" src="https://user-images.githubusercontent.com/9853255/227777428-6c8d810d-fdc8-41ab-9a59-4e0627500289.png">
