### ISSUE TITLE
Cyclic Causal Discovery Algorithms

### ISSUE THREAD

**Issue by roys8001** [cmu-phil/tetrad#1577]
The TETRAD GUI application does not support any cyclic causal discovery algorithms like CCD, CCI, LiNG as of now, right??

**Comment by jdramsey** [comment]
Well, CCD I can never get to work correctly, so I took it out of the interface. CCI for us refers to a certain test, not a search algorithm. We have code for LiNG, but it needs to be recoded.

We do have one algorithm that does well with cyclic graphs, which is FASK... let me see if I can find the paper for that...

https://www.biorxiv.org/content/10.1101/245936v1.abstract

We compared FASK and a Matlab algorithms called Two Step on a cyclic fMRI task.

**Comment by cg09** [comment]
Fask extracts cyclic models from time series with feedback in linear,
non-Gaussian systems. See
https://www.readcube.com/articles/10.1162%2Fnetn_a_00061

Some older versions of TETRAD will have Ling. Joe, where is the FASK code
and are there directions to finding 2 step on github? I don't know where
Kun put it, if he did.

Clark

**Comment by roys8001** [comment]
Thank you so much Dr. Ramsey & Dr. Glymour. This is like a big fan moment for me to get a reply from your side. I shall go through the papers that you have mentioned. Thank you so much. 

On a side note, I must mention that I am finding it difficult to run the rcausal package in R, which is an wrapper written in R for Tetrad library. There is a ccd() function for Cyclic Causal Discovery algorithm (Richardson, 1996) there but it is giving error everytime I run. The error I am getting is as follows,

> data("audiology")
> #Compute Cyclic Causal Discovery
> ccd <- ccd(df=audiology, continuous = FALSE, depth = -1, verbose = TRUE)

Error in ccd(df = audiology, continuous = FALSE, depth = -1, verbose = TRUE) : 
  unused argument (continuous = FALSE)

Could you help me with this? I am well aware of the fact that the rcausal package has not been updated since 2019  and this is the next project that you are going to take up in future.

**Comment by jdramsey** [comment]
It's interesting that you should ask this question right at this time; just this week (including work in the last few hours by me) we've been trying to come up with a want to use the most recent Tetrad jar for including Tetrad in R. Maybe you want to be a Guinea pig? This is fresh code; there could still be bugs, but your feedback would be invaluable.

Here's the project--the part of the project for incorporating Tetrad into Python already works quite well, but we just added a Python class, TetradSearch, that seems to work quite well from R. I'd be very curious whether you can follow the instructions for getting it to work and if not where you get stuck.

https://github.com/cmu-phil/py-tetrad

**Comment by jdramsey** [comment]
I did not put CCD into this build, though I could if you really want to use it. I've just had so much trouble with accuracy for it.

**Comment by jdramsey** [comment]
And I'm glad you're able to use Tetrad--that's nice!

**Comment by roys8001** [comment]
Thanks Dr Ramsey. I am happy to be the guinea pig for this noble cause. Although it would be helpful if you could elaborate a little bit more on what you want me to do. Actually I have never called a python class from R and I am very much excited to learn and follow your instructions.

**Comment by jdramsey** [comment]
I will add it and organize the instructions a little better. :)

**Comment by roys8001** [comment]
Thank you so much, Dr Ramsey.

**Comment by jdramsey** [comment]
I have to say, the setup for this may. be annoying but the payoff of going through all the setup will I think be very nice--it will be so easy to run Tetrad algorithm in R!

@bja43 and I thought up this way of doing it yesterday. Very experimental, but very curious about what you think.

Why is it annoying to set this up? There are many steps.

* You need to have Java installed. You already do I think.
* You need to set JAVA_HOME somehow to your Java path.
* You need to have Python installed. You may or may not have that installed yet.
* If you're using RStudio, you apparently need to launch from a Terminal window on a Mac. Haven't tested Windows yet. Otherwise, the JAVA_HOME variable doesn't seem to take.
* You need to install the 'reticulate' package in R (easy peasy).
* You need to tell Reticulate/R where your Python is.

The last two steps you can get from the [Reticulate doc page](https://rstudio.github.io/reticulate/):

library(reticulate)
use_python("/usr/local/bin/python")

where the Python path is the path to your Python. You can type 'which Python' or something in a Terminal window to get this.

* You need to clone the py-tetrad repository from GitHub. 

Then if you've done all that, you can open one of the example R files in py-tetrad:

https://github.com/cmu-phil/py-tetrad/tree/main/pytetrad/R

Then adjust the path in it to your working directory (if it isn't right already), select all, and run. That should run FGES on the example file and print out the graph in PCALG format.

This is my _first attempt to do this_ so if any of that seems difficult let me know and I'll expand the instructions! I'm guessing you won't have too much trouble though.

**Comment by jdramsey** [comment]
Also, I'm not sure yet I'm returning a graph compatible with the one in rcausal or whether that matters. I'm returning a graph in the PCALG general graph format.

**Comment by jdramsey** [comment]
I'm editing the above for clarity. Once the instructions are clear, I'll put them into the py-tetrad package in the [R README](https://github.com/cmu-phil/py-tetrad/blob/main/pytetrad/R/REAMDE.md).

**Comment by jdramsey** [comment]
Actually one more edit; let me put these instructions in the [R README](https://github.com/cmu-phil/py-tetrad/blob/main/pytetrad/R/REAMDE.md) file in the py-tetrad repo.

**Comment by roys8001** [comment]
Thank you so much, Dr Ramsey. It would be helpful if you give me sometime to go through the steps and apply it on my MAC.

**Comment by jdramsey** [comment]
Take your time. Also, if a step is not working for you, let me know, but you're using a Mac; I think it should work in principle.

**Comment by roys8001** [comment]
I was trying to follow what you explicitly wrote in the README file for calling the python class from R. 
However when I am sourcing the run_continuous.py file, the following error is shown. 

Error: ModuleNotFoundError: No module named 'jpype'

However I must mention that I have python 3.11 installed on my MAC with pycharm as an IDE. I have installed JPype in the pycharm terminal with the following command - 

>  pip install JPype1

And there was no error during the installation process. Could you point me to the direction where I am doing wrong?

**Comment by jdramsey** [comment]
I'll add a note--installing JPype was part of the installation process for setting up py-tetrad. Let me fix that.

**Comment by jdramsey** [comment]
OK, I pasted the py-tetrad install instructions into that page; I may simplify it though, especially since as you say all you really need to do it type pip install JPype1. Let me think about it. Anyway here's the revision:

https://github.com/cmu-phil/py-tetrad/blob/main/pytetrad/R/README.md

**Comment by jdramsey** [comment]
Yeah hold on let me simplify.

**Comment by jdramsey** [comment]
OK, I simplified it. Hopefully it's clearer!

**Comment by jdramsey** [comment]
I simplified it more... (I'm really bad at writing instructions like this and have to go through several revisions...)
