### ISSUE TITLE
Unidentified likelihood encountered for test 

### ISSUE THREAD

**Issue by zackzhou0814** [cmu-phil/tetrad#1772]
Hi, I'm running the PC algorithm with a CSV file that contains dozens of columns which are the features. The features are mixed with continuous and discrete variables. When I run the PC algorithm, I encountered an error message: 
![Image_20240520184153](https://github.com/cmu-phil/tetrad/assets/59987174/a4b89fbf-2747-4048-86cf-f3fa449a5b02)
Race, Age, Area and CCI are all the features in the CSV file, where Race and Area are discrete variables, CCI and Age are continuous variables. Could you give me some advice? Thank you.

**Comment by jdramsey** [comment]
Huh, interesting. Why is the likelihood undefined? Is there a singularity in the data? Let me think about it...

Do you have the same problem when you use the "degenerate Gaussian" test?

**Comment by ps7z** [comment]
yes.

Peter

Peter Spirtes
Marianna Brown Dietrich Professor and Head of Philosophy
Carnegie Mellon University
***@***.***

**Comment by jdramsey** [comment]
Interesting. I looked in the code; these are cases where there was a singularity in the likelihood calculation. Let me think about whether there's a way to finesse that with generalized matrices. I included generalized matrix calculations in several of the scores and tests (because I now know how to invert a matrix using pseudoinverses), but not this.

**Comment by jdramsey** [comment]
Oh I see for the conditional Gaussian these must be cases where the determinant is zero:
```
    private double gaussianLikelihood(int k, Matrix sigma) {
        return -0.5 * log(sigma.det()) - 0.5 * k * (1 + ConditionalGaussianLikelihood.LOG2PI);
    }
```
That's the only way that function could be undefined. Wait, no, that should evaluate to negative infinity, and then this calculation:
```
            if (!X.isEmpty()) {
                try {

                    // Determinant will be zero if data are linearly dependent.
                    double gl = gaussianLikelihood(k, cov(getSubsample(continuousCols, cell)));

                    if (!Double.isNaN(gl)) {
                        c2 += a * gl;
                    }
                } catch (Exception e) {
                    // No contribution.
                }
            }
```
Let's ask our friend ChatGPT:
```
public class LogExample {
    public static void main(String[] args) {
        double mathLogResult = Math.log(0);
        double fastMathLogResult = org.apache.commons.math3.util.FastMath.log(0);

        System.out.println("Math.log(0): " + mathLogResult);
        System.out.println("FastMath.log(0): " + fastMathLogResult);
    }
}

Output:
Math.log(0): -Infinity
FastMath.log(0): -Infinity
```
So this is a bug! This is a bug! I'm not catching the right condition! So can log(x) be NaN, undefined? Can the determinant be negative? Also yes! Can a determinant be negative?
```
Consider a 2x2 matrix:
 A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} 

The determinant of ( A ) is calculated as:
 \text{det}(A) = 1 \cdot 4 - 2 \cdot 3 = 4 - 6 = -2 
```
The log of a negative determinant would be evaluated as NaN! I no! There must be an absolute value sign here! One second, let me try it.

**Comment by jdramsey** [comment]
The conditional Gaussian divides the full sample size into "cells," each of which has a sample size. A further consideration is that there can't be less than two rows or one column in order to calculate a covariance matrix. I'm finding in simulation that if there are less than 4 rows, the calculation is inaccurate, though perhaps this should be made a parameter, "minSampleSizePerCell," default 4, minimum 2. Let me do that. That will give the user some control. The determinant of the covariance matrix could still be zero, in which case the cell should be skipped.

OK, I think that cleans up conditional Gaussian. Let me look at Degenerate Gaussian.

**Comment by jdramsey** [comment]
The DG score was able to take the pseudoinverse parameter, so I added it. However, the DG LRT test is returning independence judgments with NaN p-values, which is the main issue. This was the original complaint. There are two places in the code throwing this exception:
```
        double lik0 = ret1.getLik() - ret2.getLik();
        double dof0 = ret1.getDof() - ret2.getDof();
...
        if (Double.isNaN(lik0)) {
            throw new RuntimeException("Undefined likelihood encountered for test: " + LogUtilsSearch.independenceFact(x, y, _z));
        } else {
            pValue = 1.0 - new ChiSquaredDistribution(dof0).cumulativeProbability(2.0 * lik0);
        }
```
I believe I've fixed this as above by adding absolute value signs to the determinants:
```
        double dof = (A_.length * (A_.length + 1) - B_.length * (B_.length + 1)) / 2.0;
        double ldetA = log(abs(getCov(rows, A_).det()));
        double ldetB = log(abs(getCov(rows, B_).det()));
```

OK, I believe this is all fixed now for both CG and DG. I'll soon make a new snapshot build of Tetrad you can use. Again, thanks for pointing out this problem; I was unaware of it!

**Comment by zackzhou0814** [comment]
Thank you so much for your responses! If you could, could you deliver the fixed version as soon as possible? Also, I have tried degenerate Gaussian but it's been running for several hours and it still shows processing.... is this normal?

**Comment by zackzhou0814** [comment]
The maximum category I have is 5(1, 2, 3, 4, 5) for a discrete variable. I have about 20 features and 22290 rows mixed of continuous and discrete variables. Could it be because my data is too large?

**Comment by jdramsey** [comment]
So I'm trying to think--maybe you can help. What DG is doing is making a separate column for (m - 1) categories for a variable with m categories

**Comment by zackzhou0814** [comment]
In my data, I have 20 features/columns, and I'm trying to use the PC algorithm. My coworker told me he encountered the same problem before when he used more than 18 features, and he couldn't get the graph either. It worked for him after he reduced the number of features/columns to 18 or fewer. Maybe that's the cause of the issue?

**Comment by jdramsey** [comment]
One issue with PC that I've noticed is that if you don't set the depth to something small, like 3, the algorithm can start to do independence tests with a lot of conditioning variables, which in the case of discrete or mixed data may not be very helpful. So that's one thing you could do, if you haven't already done it: Limit the depth.

Another thing you could do is to try the BOSS algorithm, which is also in Tetrad. It's a permutation-based algorithm, which sounds like it might be slower than PC, but in practice it is not; it's actually much faster in a lot of cases, due to an amazing optimization effort by Bryan Andrews. Here's the paper for it:

Andrews, B., Ramsey, J., Sanchez Romero, R., Camchong, J., & Kummerfeld, E. (2023). Fast Scalable and Accurate Discovery of DAGs Using the Best Order Score Search and Grow Shrink Trees. Advances in Neural Information Processing Systems, 36.

OK, I have finished my updates to Tetrad, for the most part. I have someone coming by at 2, but let me see if I can't make you a snapshot build real quick...

**Comment by jdramsey** [comment]
Also, I should say the BOSS algorithm is considerably more accurate than PC--see the figures it the paper.

**Comment by jdramsey** [comment]
I made a snapshot build with the above fix. This isn't a perfect build, as I've been expanding the Paths dialog in the Graph box, and I'm not quite done with that work yet, but so long as you're OK with that, feel free to use this. I hope to finish that work and post another snapshot in the next few days.

https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/cmu-phil/tetrad-gui/7.6.5-SNAPSHOT/tetrad-gui-7.6.5-20240521.175926-4-launch.jar

**Comment by zackzhou0814** [comment]
Got it. I will try them out! Thank you very much!

**Comment by jdramsey** [comment]
I'll close this for now; if you try it and it doesn't work, feel free to re-open it... :)
