### ISSUE TITLE
Structure learning algorithms

### ISSUE THREAD

**Issue by haluk** [cmu-phil/tetrad#194]
What structure learning algorithms does Tetrad provide? I checked the source code but couldn't find Hill Climbing.

**Comment by jdramsey** [comment]
Sorry, we don't have a proper implementation of MMHC, but you should check
out FGS, which does a GES-style search for the maximum BIC or BDeu score.

On Sat, Jun 4, 2016 at 6:49 PM, Haluk Dogan <notifications@github.com>
wrote:

> What structure learning algorithms does Tetrad provide? I checked the
> source code but couldn't find Hill Climbing.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/194>, or mute the thread
> <https://github.com/notifications/unsubscribe/AJZZR35vkJ8rEP80ixIGAD4VUe4B6jSVks5qIgD0gaJpZM4IuPJ9>
> .
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
I should also say, Tetrad, of course, has all of the algorithms described
in Spirtes et al., Causation, Prediction and Search, which goes without
saying since it's our department. So it has PC, FCI, BPC, and also CCD,
GFCI, and many others. If you haven't read Causation, Prediction, and
Search, it's a good read, so long as you avoid the proofs.

On Sat, Jun 4, 2016 at 7:53 PM, Joseph Ramsey <jdramsey@andrew.cmu.edu>
wrote:

> Sorry, we don't have a proper implementation of MMHC, but you should check
> out FGS, which does a GES-style search for the maximum BIC or BDeu score.
>
> On Sat, Jun 4, 2016 at 6:49 PM, Haluk Dogan <notifications@github.com>
> wrote:
>
>> What structure learning algorithms does Tetrad provide? I checked the
>> source code but couldn't find Hill Climbing.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/cmu-phil/tetrad/issues/194>, or mute the thread
>> <https://github.com/notifications/unsubscribe/AJZZR35vkJ8rEP80ixIGAD4VUe4B6jSVks5qIgD0gaJpZM4IuPJ9>
>> .
>>
>
>
>
> --
> Joseph D. Ramsey
> Special Faculty and Director of Research Computing
> Department of Philosophy
> 135 Baker Hall
> Carnegie Mellon University
> Pittsburgh, PA 15213
>
> jsph.ramsey@gmail.com
> Office: (412) 268-8063
> http://www.andrew.cmu.edu/user/jdramsey
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
But hill climbing is someone else's project. I've implemented it--as you
can probably see in the code--but i don't put it in the interface because I
haven't taken the time to optimize it in the way the authors have. You can
check out their project for that. In my version, it doesn't do as well as
FGS, so you should definitely go with a version that's more competitive.

On Sun, Jun 5, 2016 at 12:57 PM, Joseph Ramsey <jdramsey@andrew.cmu.edu>
wrote:

> I should also say, Tetrad, of course, has all of the algorithms described
> in Spirtes et al., Causation, Prediction and Search, which goes without
> saying since it's our department. So it has PC, FCI, BPC, and also CCD,
> GFCI, and many others. If you haven't read Causation, Prediction, and
> Search, it's a good read, so long as you avoid the proofs.
>
> On Sat, Jun 4, 2016 at 7:53 PM, Joseph Ramsey <jdramsey@andrew.cmu.edu>
> wrote:
>
>> Sorry, we don't have a proper implementation of MMHC, but you should
>> check out FGS, which does a GES-style search for the maximum BIC or BDeu
>> score.
>>
>> On Sat, Jun 4, 2016 at 6:49 PM, Haluk Dogan <notifications@github.com>
>> wrote:
>>
>>> What structure learning algorithms does Tetrad provide? I checked the
>>> source code but couldn't find Hill Climbing.
>>>
>>> —
>>> You are receiving this because you are subscribed to this thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/cmu-phil/tetrad/issues/194>, or mute the thread
>>> <https://github.com/notifications/unsubscribe/AJZZR35vkJ8rEP80ixIGAD4VUe4B6jSVks5qIgD0gaJpZM4IuPJ9>
>>> .
>>>
>>
>>
>>
>> --
>> Joseph D. Ramsey
>> Special Faculty and Director of Research Computing
>> Department of Philosophy
>> 135 Baker Hall
>> Carnegie Mellon University
>> Pittsburgh, PA 15213
>>
>> jsph.ramsey@gmail.com
>> Office: (412) 268-8063
>> http://www.andrew.cmu.edu/user/jdramsey
>>
>
>
>
> --
> Joseph D. Ramsey
> Special Faculty and Director of Research Computing
> Department of Philosophy
> 135 Baker Hall
> Carnegie Mellon University
> Pittsburgh, PA 15213
>
> jsph.ramsey@gmail.com
> Office: (412) 268-8063
> http://www.andrew.cmu.edu/user/jdramsey
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by haluk** [comment]
Did you commit your implementation to tetrad project?

**Comment by jdramsey** [comment]
Yes but I would not use it if I were you. It's not in the interface. I may
delete it at some point. But these are odd questions. You're looking at the
repository. Can't you see what's in it?

On Sunday, June 5, 2016, Haluk Dogan <notifications@github.com> wrote:

> Did you commit your implementation to tetrad project?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/194#issuecomment-223826916>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJZZR1ZZO4UxrFOSQCdU_d9m7XYZTENpks5qIwxVgaJpZM4IuPJ9>
> .
>


-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by haluk** [comment]
No, I can't see. The last commit was 4 days ago as of today.

**Comment by jdramsey** [comment]
Just getting back to looking at issues. I'm still confused by your question, maybe you can clarify. The implementation of MMHC has been there for years; it's not new. It's just not right like I said. The constraint part is OK, but the hill climbing not the authors' hill climbing; I substituted my own hill climbing algorithm in for that. So I wouldn't use it, certainly not for publication. That's all I meant.
