### ISSUE TITLE
Variable appears multiple times in knowledge box

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#206]
Reproduce by 
1) add data box, knowledge box, search box
2) connect all
3) set knowledge
4) save knowledge
5) open up knowledge box and see same variables appearing > 1

**Comment by jdramsey** [comment]
Thanks.

On Tue, Jun 14, 2016 at 11:10 AM, Jeremy Espino <notifications@github.com>
wrote:

> Reproduce by
> 1) add data box, knowledge box, search box
> 2) connect all
> 3) set knowledge
> 4) save knowledge
> 5) open up knowledge box and see same variables appearing > 1
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/206>, or mute the thread
> <https://github.com/notifications/unsubscribe/AJZZR0P7UIuWBqGHpnNxfAHvtAYzeSZfks5qLsRVgaJpZM4I1bhj>
> .
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
This sounds like an indexing problem. I'll look at it.

**Comment by jdramsey** [comment]
OK,I think this is fixed in 'experimental'--there were some underlying issues with poor encapsulation of knowledge. I don't know if I fixed all of the problems, but I fixed a lot of them. I can't get this to fail anymore.

Once the current round of fixes and improvements is done I'll push to 'development' and re-post. It's going to be a doozy of an upgrade.
