### ISSUE TITLE
Add all algorithms in tetrad cmd to causal cmd

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#216]
We should have flags that indicate users will be using non-big data algorithms.

**Comment by jdramsey** [comment]
Does this depend on getting the algorithm wrappers right? I guess you can start with the ones that are done. It occurred to me that some of the algorithms can take knowledge, and that's not in the Algorithm interface, so that will have to be added. (It can be passed in via a constructor, I guess; maybe that's good enough.)

**Comment by jdramsey** [comment]
All of the algorithms comparison algorithms have been added to the Tetrad interface in 'experimental'.

**Comment by jdramsey** [comment]
Yeah I thought about this for a while, and I think we should be targeting not the algorithms in Tetrad CMD but rather the algorithms in the Algorithm Comparison API. And not all of them, but selected ones.

**Comment by jdramsey** [comment]
@espinoj I think this is done, no?

**Comment by espinoj** [comment]
@jdramsey  It isn't but it is low priority.  I am assigning to Kevin.

**Comment by espinoj** [comment]
Making an issue in causal-cmd project and closing
