### ISSUE TITLE
problems with 'knowledge'

### ISSUE THREAD

**Issue by kingfish777** [cmu-phil/tetrad#218]
In latest Tetrad GUI:
 * knowledge changes (changes in variables per level) are not consistently changed post-save
 * when I attempt to click on one variable, another variable is moved instead to target area
 * shift function for moving variables is tricky to use

**Comment by jdramsey** [comment]
Thanks.

On Tue, Jun 21, 2016 at 3:52 PM, Kingfish Threesevens <
notifications@github.com> wrote:

> In latest Tetrad GUI:
>
>    - knowledge changes (changes in variables per level) are not
>    consistently changed post-save
>    - when I attempt to click on one variable, another variable is moved
>    instead to target area
>    - shift function for moving variables is tricky to use
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/218>, or mute the thread
> <https://github.com/notifications/unsubscribe/AJZZRxGh2iEP91e2NBCmK2sagbV_2FMCks5qOEDmgaJpZM4I7G4b>
> .
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
I have to think about how to clear up the knowledge problems once and for all. I will ponder it.

**Comment by jdramsey** [comment]
This one:

* knowledge changes (changes in variables per level) are not consistently changed post-save

I'm going to fix by removing global persistence across runs. Working on it.

These ones:

* when I attempt to click on one variable, another variable is moved instead to target area
* shift function for moving variables is tricky to use

I don't know what to do about yet; they seem to be a problem with Java, not Tetrad. I'll try though.

**Comment by jdramsey** [comment]
I think I've fixed the first one. (I'm working in the branch 'experimental.') Like I said I was going to do, I got rid of the global saving of knowledge information and encapsulated the use of knowledge better. I can't get it to fail now. If it still fails, please reopen the issue and comment on it.

The second issue seems to be fixed as well. That must have been caused by the interaction of different knowledge objects.

The third one I'm having no trouble with anymore. I think for the same reason.

I believe this is fixed. But like I said if it's not, reopen it. It's all in the 'experimental' branch for now. Once I get done with this round of updates and fixes I'll push everything to 'development' and re-post.

**Comment by kingfish777** [comment]
Great, Thanks!
 -S
