### ISSUE TITLE
FOFC doesn't scale with sample size

### ISSUE THREAD

**Issue by adambrodie** [cmu-phil/tetrad#23]
FOFC isn't scaling with sample size.
 
Any kind of pure measurement model, FOFC slow with large N, e.g., 10,000.

**Comment by jdramsey** [comment]
95% of the time is being spend in the getCorrelationMatrix() method of BoxDataSet. That's not right.

**Comment by jdramsey** [comment]
Oh how interesting. If I use the covariance matrix instead of the correlation matrix in ContinuousTetradTest, FOFC returns almost instantaneously even for large models with incredibly good answers. Now the question is, why does ContinuousTetradTest need the correlation matrix, and does it need that everywhere?

**Comment by ekummerfeld** [comment]
I don't think the correlation matrix is needed but I don't recall the details. Certainly, lines like " double product1 = rho.get(a0, a0) * rho.get(a3, a3) - rho.get(a0, a3) * rho.get(a0, a3);" are kind of silly when rho is a correlation matrix, since rho.get(a0, a0) etc. would just be 1. I think the wishart test at least will work just fine for a covariance matrix instead of a correlation matrix.

**Comment by jdramsey** [comment]
According to the big book of truth (CPS), p. 150, vanishing tetrads are sums of products of correlations. Before jumping to any conclusions, let me first try making a correlation matrix by getting the covariance matrix and scaling it. I'm interested to see if that gives a good (and fast) result too.

**Comment by jdramsey** [comment]
Peter says Drton's paper uses covariances. I'll use covariances.

**Comment by jdramsey** [comment]
This is now fixed in the master branch. Run git pull https://github.com/cmu-phil/tetrad.git master in the terminal to get the fix.
