### ISSUE TITLE
How does SearchGraphUtils.patternForDag method work?

### ISSUE THREAD

**Issue by haluk** [cmu-phil/tetrad#231]
Why do we use patternForDag method to compare true network and learnt one?

**Comment by jdramsey** [comment]
Because a method like PC doesn't output a DAG; it outputs a pattern. Some
of the edges are undirected. If you compare it the true DAG, you will
penalize the result for not orienting some edges. But it's not supposed to!

Joe

On Tue, Jul 12, 2016 at 12:33 PM, Haluk Dogan <notifications@github.com>
wrote:

> Why do we use patternForDag method to compare true network and learnt one?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/231>, or mute the thread
> <https://github.com/notifications/unsubscribe/AJZZRxXsx6MCAjZ2xmGXgfiRV1hIngOJks5qU8HXgaJpZM4JKkpa>
> .
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
Let me know if this is still open.
