### ISSUE TITLE
Opening mutiple sessions

### ISSUE THREAD

**Issue by rubencmu** [cmu-phil/tetrad#432]
@jdramsey From the ccd-helpdesk:

--The logging for the new Tetrad is much less verbose. The columns of loaded data and their domains are no longer printed. Neither are the edges of found graphs.  

-- I can no longer open multiple Tetrad sessions at a time  

Any information about this topics is welcome.

**Comment by espinoj** [comment]
@kvb2univpitt I remember verbose logging got turned off at some point by default.  Can you turn it back on?

**Comment by jdramsey** [comment]
I don't understand. I can open multiple sessions. I can't open the same one twice, but if they're different I can. I wonder how to make this break?

**Comment by espinoj** [comment]
@rubencmu I spoke to Kevin and he isn't sure if this is related to console logging in general.  He did note that during a search he suggested Joe turn off logging because it slowed down the search significantly.  Can you collect some more information from the user?  Is this when the search is running?  Is it on the console or some other log file?

**Comment by kvb2univpitt** [comment]
@espinoj @rubencmu  I only suggested to Joe to reduce the number of System.out.println() in the JUnit tests so that the test can run a little faster.  This should not affect the actually logging when running algorithms.
