### ISSUE TITLE
Can't launch multiple instances of Tetrad simultaneously.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#556]
Don't kill the messenger. I'm just reporting that Kun has expressed frustration at not being able to launch multiple instances of Tetrad at the same time. When you run an algorithm, it blocks, and you can't run another. He wants to get around that by launching multiple Tetrads.

**Comment by chirayukong** [comment]
@jdramsey I think we made the one-running-instance-only feature for a purpose. We integrate an HPC module to the Tetrad and it comes with the built-in lightweight HyperSQL database. It allows only one connection to its database. 

However, in order to solve your problem, I propose a solution that we can make Tetrad running multiple workspaces (and multiple sessions) like the typical software suite, such as Microsoft Office. We can have only a one-instance Tetrad running in their own workspace (and its own sessions). Once, a user wants to run another session, then create a new session (it is like creating a new tab in a browser) or a new workspace (it works more or less like opening a new browser window). We can also integrate these running threads into the job queue (task manager if you will) that we already have, and also @kvb2univpitt is working on the way that we can signal the thread to terminate it gracefully. 

In case that a user instantiates a new Tetrad, instead of showing errors, the Tetrad should implicitly create a new session (a new tab) within the new workspace (a new window).

What do you think? @jdramsey @espinoj :-)

**Comment by jdramsey** [comment]
Obviously, I'd like to know what @espinoj says, but from the sounds of it, that would be great! The only issue I can think of at the moment is that the progress bar that comes up when you run an algorithm currently blocks Tetrad from doing anything else. Is there a way to get it to block only for the displayed window?

**Comment by chirayukong** [comment]
We can make it run as a background process (like submitting a job to PSC, which we already have this feature), so there is nothing blocking a displayed window. @jdramsey

**Comment by jdramsey** [comment]
@chirayukong That sounds great!

**Comment by jdramsey** [comment]
This is fixed since the calls to the server have been removed.
