### ISSUE TITLE
Multi datasets in DataLoader don't allow single dataset algorithms in Search

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#612]
When multiple datasets are loaded in the Data Loader and an arrow drawn to a search box, currently only the multi-dataset algorithms are shown. But the single dataset algorithms should also be shown. The behavior for these should be to run the algorithm on each dataset separately and show the list of results. This what's done if you do several runs in the simulator and then search.

I think.

**Comment by yuanzhou** [comment]
Because the Search (algo chooser) checks if there are multiple datasets and only displays the algorithms that can handle multiple datasets. But if the single dataset algorithms are also supposed to be in the list, then how can you run just on one of the datasets in the Search? I don't see it allows users to specify which file to run. I thought whenever you gun a search by choosing an algorithm, it runs on all the loaded datasets.

**Comment by jdramsey** [comment]
Skype sometime? Maybe I have the wrong idea... Should work though. You just produce a list of output graphs.

**Comment by yuanzhou** [comment]
I'll first discuss this with the team during our daily stand-up today to see if there's any other insights/understandings before we find a time to talk.

**Comment by yuanzhou** [comment]
@jdramsey I just discussed this with the team and @chirayukong explained how this works. Just to confirm with you:

Regardless of single dataset or multiple datasets being loaded, the algo chooser should show all algorithms.

We can remove the filtering very easily.

**Comment by espinoj** [comment]
Did this get fixed @yuanzhou ?

**Comment by yuanzhou** [comment]
@espinoj It was fixed in Kevin's branch with other UI changes. Hasn't pushed to development yet.

**Comment by jdramsey** [comment]
@yuanzhou Thanks! That will be a huge help.
