### ISSUE TITLE
Clark: TsFCI needs a better error message when you (incorrectly) input data that is not a time series.

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#652]
TsFCI needs a better error message. Here is the error message when you (incorrectly) input data that is not a time series. 
![image](https://user-images.githubusercontent.com/313721/34834581-57907692-f6c0-11e7-99e6-ed298c132be1.png)

**Comment by dmalinsk** [comment]
Agreed. I'm not modifying things in the GUI these days, too much has
changed since I implemented this. Joe, do you mind tracking down where the
error message comes from and make it more informative, e.g., "This
algorithm requires a (labeled) time series data set as input." ?
(labeled in the sense of X1 X1:1 X1:2 X2 X2:1 X2:2...)

**Comment by yuanzhou** [comment]
@jdramsey I can fix this, can you tell me how to check if the input data is time series?

**Comment by jdramsey** [comment]
It should implement TimeSeriesData, I think. If you load data in from a file and then convert it to a time series it's of this class. If you simulate a time series, it's of this class.

@yuanzhou

**Comment by yuanzhou** [comment]
Addressed.

![capture](https://user-images.githubusercontent.com/195873/35300845-c2cb88de-0057-11e8-90b0-2aff7befc9f2.PNG)

It seems we should also add this message to TsGFCI.

**Comment by yuanzhou** [comment]
https://github.com/cmu-phil/tetrad/commit/8cd651aaa34d46b82be4a0adbfb652305ebe69c3

**Comment by yuanzhou** [comment]
Got the same "-1" error message with TsGFCI. Will do the same fix.
