### ISSUE TITLE
Clark: Edits in boxes have no "undo"

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#678]

**Comment by espinoj** [comment]
Is this something that used to work and no longer does?

**Comment by espinoj** [comment]
Reported by Clark, this is an enhancement

**Comment by jdramsey** [comment]
@espinoj Just a comment, I was mentioning to Kevin the other day that originally Richard had suggested that for each box, there be a cancel button that allows the results in the box to be canceled and not saved to the box. And there is code for this in Tetrad, somewhere in the SessionNode class I think--look for MarshalledObject. The problem is for some of the boxes the contents can be very large, so making a copy could easily take a lot of time and cause the GUI to crash--for instance, the Data box. 

@kvb2univpitt

**Comment by jdramsey** [comment]
This is working correctly
