### ISSUE TITLE
Edge Coefficient Value Disappear On Mouseover Event

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#695]
Coefficient value of an edge disappear whenever the edge is mouse hovered in Graphical Editor.

**Comment by yuanzhou** [comment]
Example of this issue.

![capture1](https://user-images.githubusercontent.com/195873/35645012-9107cfb4-0698-11e8-8317-cac909dbfbb3.PNG)

![capture2](https://user-images.githubusercontent.com/195873/35645013-924ac070-0698-11e8-9a2c-3060a51822b4.PNG)

**Comment by yuanzhou** [comment]
Another example:

![capture1](https://user-images.githubusercontent.com/195873/35645230-33b3e356-0699-11e8-8c38-c6ed32a1b4a8.PNG)

![capture2](https://user-images.githubusercontent.com/195873/35645233-353114e2-0699-11e8-9a37-d7fc6cfd4562.PNG)

**Comment by yuanzhou** [comment]
@jdramsey I think I found out the cause. Those coefficent values are jLabels, and whenever we mouse over the edge, the edge type label (X2-->X2) shows up and overlaps the coefficient label. To solve this problem, we'll just need to show the edge type in a tooltip instead of label.

Can you please point me to the file that creates the edge type label when we mouse over an edge in a graph?

**Comment by jdramsey** [comment]
I'm thinking...it's in AbstractWorkbench, line 576, setEdgeLabel.
