### ISSUE TITLE
Simulation Box Data Box

### ISSUE THREAD

**Issue by cg09** [cmu-phil/tetrad#769]
Using the latest release,  if a data set is created in the Simulation Box, which is then connected to a Data Box, and a column of entries is removed from the Data Box, the same entries are removed from the Simulation Box. That should not happen.

**Comment by yuanzhou** [comment]
@kvb2univpitt since you fixed the Simulation bugs, can you also take a look at this issue? My guess is the simulation data is stored to the same data model.

**Comment by kvb2univpitt** [comment]
@cg09 The reason why this happens is because the data box is just pointing to the data model in the simulation box.  We can create a deep copy so that changing the data in the data box will not affect the data in the simulation box.  The only downfall with doing a deep copy is that it may cause performance issue if the data is very large.  Basically, we have to allocate a chunk of memory each time a data box is connected to the simulation box.  Do you think we should proceed with the deep copy?

**Comment by jdramsey** [comment]
@kvb2univpitt @cg09 How about this option? Just look to see how big the dataset is. Number of variables times the number of rows. It there are more than, say, 5000 cells in the data, put up a dialog asking the user if they want to make a copy of the data. Otherwise, just go ahead and make the copy.

**Comment by jdramsey** [comment]
@kvb2univpitt I think we can just punt on this and do the deep copy, as you say. You're right, it would solve the problem.

**Comment by jdramsey** [comment]
This was fixed.
