### ISSUE TITLE
Use of knowledge in ccd-web vs tetrad gui

### ISSUE THREAD

**Issue by cabal-cmu** [cmu-phil/tetrad#790]
Hi,

A question from the CCD helpdesk:

A user is using ccd web, FGES + knowledge file. And she is reporting that there are some directed edges that show up in output graph that shouldn't be there given the tier knowledge provided. I replicate the run and indeed there are directed edges that shouldn't be there given the knowledge.

The user also reports that using the same knowledge and data in the Tetrad GUI works properly, and edges that are prohibited in the knowledge tiers are indeed absent in the final output, as opposed to the ccd web result.

Is there something incorrect about how the knowledge is being processed in the ccd web app ?

I attached the files to replicate the run. FGES is run with the default parameters in the ccd web app.
Please remove the txt extension to the knowledge file, as I needed to include it so Github would accept the file.

[data.txt](https://github.com/cmu-phil/tetrad/files/2058443/data.txt)

[knowledge.prior.txt](https://github.com/cmu-phil/tetrad/files/2058447/knowledge.prior.txt)

**Comment by kvb2univpitt** [comment]
The bug is definitely not with Causal Web.  Causal Web merely passes the inputs as a CLI command to causal-cmd.  I ran just causal-cmd and got the same bug.  I have looked into causal-cmd.  It seems like causal-cmd is passing in the knowledge file correctly to Tetrad.  Not sure why this is happening.

**Comment by kvb2univpitt** [comment]
After going through the issue with @espinoj, we realized that the problem is with Tetrad.  The knowledge file has 11 tiers.  But, Tetrad GUI only showing two tiers when reading in the knowledge file.  It seems like Tetrad GUI is not taking in more than two tiers.  I will create a different issue for this.

**Comment by cabal-cmu** [comment]
Thanks.
